'use server'

/**
 * lib/message-actions.ts — human-initiated server actions for the review queue
 * (T7.3-T7.6). The AI draft itself is generated by lib/ai/draft-runner.ts (service
 * role, like ai_run/research_run); everything here is a person acting on their own
 * RLS-scoped client, same as lib/company-actions.ts and lib/research-actions.ts.
 */
import { revalidatePath } from 'next/cache'
import { createServerClient } from './supabase/server'
import { requirePermission, canWrite, canApprove, canReleaseCommercial } from './session'
import { writeAudit, AUDIT } from './audit'
import { sha256 } from './messages'
import { scanPatterns } from './guardrails'
import { generateFirstTouch, generateFollowup, DraftError } from './ai/draft-runner'
import { AIError } from './ai/client'
import { createDraft, ConnectorError } from './gmail'

export type MessageActionState = {
  ok: boolean
  error?: string
  companyId?: string
  messageId?: string
  gmailWarning?: string
  gmailDraftId?: string
}

const isUuid = (s: string) => /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(s)

/**
 * T8.3 — create the Gmail draft for an approved message. Deliberately never throws:
 * a connector failure must surface as a visible, retryable state, not roll back the
 * human approval that already happened. Only the message's own approver may do this
 * — message_update's RLS "approving" branch requires approved_by = auth.uid() on the
 * resulting row, which a gmail_draft_id-only update still has to satisfy, and drafts
 * belonging in the approver's own mailbox is also just correct per the mock's "Safety
 * rails" card ("Per-user tokens... drafts appear in the approver's own mailbox").
 */
async function attemptGmailDraft(
  supabase: Awaited<ReturnType<typeof createServerClient>>,
  messageId: string,
  actor: { id: string; fullName: string; email: string },
): Promise<{ draftId: string } | { warning: string }> {
  const fail = async (warning: string) => {
    await writeAudit({
      actorId: actor.id,
      actorLabel: actor.fullName,
      event: AUDIT.GMAIL_FAILED,
      objectType: 'message',
      objectId: messageId,
      detail: warning,
    })
    return { warning }
  }

  const { data: message } = await supabase
    .from('message')
    .select('subject, ai_body, human_body, contact_id')
    .eq('id', messageId)
    .single()
  if (!message || !message.contact_id) return fail('No contact on this message — cannot create a Gmail draft.')

  const { data: contact } = await supabase.from('contact').select('email').eq('id', message.contact_id).single()
  if (!contact?.email) return fail('This contact has no email on record — cannot create a Gmail draft.')

  try {
    const { draftId, threadId } = await createDraft({
      profileId: actor.id,
      from: `${actor.fullName} <${actor.email}>`,
      to: contact.email,
      subject: message.subject,
      body: message.human_body ?? message.ai_body,
    })
    await supabase.from('message').update({ gmail_draft_id: draftId, gmail_thread_id: threadId }).eq('id', messageId)
    await writeAudit({
      actorId: actor.id,
      actorLabel: actor.fullName,
      event: AUDIT.GMAIL_DRAFT_CREATED,
      objectType: 'message',
      objectId: messageId,
      detail: `Draft ${draftId} created in ${actor.fullName}'s mailbox`,
    })
    return { draftId }
  } catch (err) {
    return fail(err instanceof ConnectorError ? err.userFacing : 'Could not create the Gmail draft.')
  }
}

/* ------------------------------------------------------------------ */
/* T7.1/T7.7 — draft the next outreach message for a company           */
/* ------------------------------------------------------------------ */

export async function draftOutreach(formData: FormData): Promise<MessageActionState> {
  let actor
  try {
    actor = await requirePermission(canWrite, 'draft outreach')
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : 'Not allowed' }
  }

  const companyId = (formData.get('companyId') as string)?.trim()
  if (!companyId || !isUuid(companyId)) return { ok: false, error: 'Missing company.' }

  try {
    let result
    try {
      result = await generateFirstTouch(companyId, actor)
    } catch (err) {
      if (err instanceof DraftError && err.message.includes('already exists')) {
        result = await generateFollowup(companyId, actor)
      } else {
        throw err
      }
    }
    revalidatePath(`/companies/${companyId}`)
    revalidatePath('/review')
    return { ok: true, companyId, messageId: result.messageId }
  } catch (err) {
    if (err instanceof DraftError) return { ok: false, error: err.message }
    if (err instanceof AIError) return { ok: false, error: err.message }
    return { ok: false, error: 'Drafting failed.' }
  }
}

/* ------------------------------------------------------------------ */
/* T7.3 — edit a draft; re-running the guardrail can clear or set a hold*/
/* ------------------------------------------------------------------ */

export async function editMessage(formData: FormData): Promise<MessageActionState> {
  let actor
  try {
    actor = await requirePermission(canWrite, 'edit a draft')
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : 'Not allowed' }
  }

  const messageId = (formData.get('messageId') as string)?.trim()
  const body = (formData.get('body') as string)?.trim()
  if (!messageId || !isUuid(messageId)) return { ok: false, error: 'Missing message.' }
  if (!body) return { ok: false, error: 'Message body cannot be empty.' }

  const supabase = await createServerClient()
  const { data: message } = await supabase.from('message').select('status, company_id').eq('id', messageId).single()
  if (!message) return { ok: false, error: 'Message not found.' }
  if (message.status !== 'awaiting_approval' && message.status !== 'held_commercial') {
    return { ok: false, error: 'This message can no longer be edited.' }
  }

  const findings = scanPatterns(body)
  const clear = findings.length === 0
  const update: { human_body: string; status?: 'awaiting_approval' | 'held_commercial'; reserved_matter?: string | null } =
    { human_body: body }

  if (clear) {
    // Any write role may clear a hold this way — once the pattern pass finds
    // nothing, there is genuinely nothing left for Commercial to release.
    update.status = 'awaiting_approval'
    update.reserved_matter = null
  } else if (actor.role !== 'commercial') {
    return {
      ok: false,
      error: `This text still touches a reserved matter (${findings[0].label}). Remove it, or ask a Commercial Authority to review.`,
    }
  } else {
    update.status = 'held_commercial'
    update.reserved_matter = findings[0].matter
  }

  const { error } = await supabase.from('message').update(update).eq('id', messageId)
  if (error) return { ok: false, error: error.message }

  await writeAudit({
    actorId: actor.id,
    actorLabel: actor.fullName,
    event: 'Draft edited',
    objectType: 'message',
    objectId: messageId,
    detail: clear ? 'Edit cleared the guardrail' : 'Edit still touches a reserved matter',
  })

  revalidatePath('/review')
  return { ok: true, companyId: message.company_id }
}

/* ------------------------------------------------------------------ */
/* T7.5 — approve / reject / request changes                           */
/* ------------------------------------------------------------------ */

export async function approveMessage(formData: FormData): Promise<MessageActionState> {
  let actor
  try {
    actor = await requirePermission(canApprove, 'approve outreach')
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : 'Not allowed' }
  }

  const messageId = (formData.get('messageId') as string)?.trim()
  if (!messageId || !isUuid(messageId)) return { ok: false, error: 'Missing message.' }

  const supabase = await createServerClient()
  const { data: message } = await supabase
    .from('message')
    .select('ai_body, human_body, company_id')
    .eq('id', messageId)
    .single()
  if (!message) return { ok: false, error: 'Message not found.' }

  const finalBody = message.human_body ?? message.ai_body
  const hash = await sha256(finalBody)

  const { error } = await supabase
    .from('message')
    .update({
      status: 'approved',
      approved_by: actor.id,
      approved_at: new Date().toISOString(),
      approved_hash: hash,
    })
    .eq('id', messageId)

  if (error) {
    // held_needs_release fires here, not in the UI, when a held draft's reserved
    // content has not been released yet — surface it as the real reason.
    if (error.message.includes('held_needs_release')) {
      return { ok: false, error: 'This draft touches a reserved commercial matter and must be released by a Commercial Authority before it can be approved.' }
    }
    return { ok: false, error: error.message }
  }

  await writeAudit({
    actorId: actor.id,
    actorLabel: actor.fullName,
    event: AUDIT.OUTREACH_APPROVED,
    objectType: 'message',
    objectId: messageId,
    detail: `Approved. sha256 ${hash.slice(0, 12)}…`,
  })

  const gmailResult = await attemptGmailDraft(supabase, messageId, actor)

  revalidatePath('/review')
  revalidatePath(`/companies/${message.company_id}`)
  return 'warning' in gmailResult
    ? { ok: true, companyId: message.company_id, messageId, gmailWarning: gmailResult.warning }
    : { ok: true, companyId: message.company_id, messageId, gmailDraftId: gmailResult.draftId }
}

/* ------------------------------------------------------------------ */
/* T8.3 — retry Gmail draft creation after a connector failure          */
/* ------------------------------------------------------------------ */

export async function retryGmailDraft(formData: FormData): Promise<MessageActionState> {
  let actor
  try {
    actor = await requirePermission(canApprove, 'create a Gmail draft')
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : 'Not allowed' }
  }

  const messageId = (formData.get('messageId') as string)?.trim()
  if (!messageId || !isUuid(messageId)) return { ok: false, error: 'Missing message.' }

  const supabase = await createServerClient()
  const { data: message } = await supabase
    .from('message')
    .select('status, approved_by, gmail_draft_id, company_id')
    .eq('id', messageId)
    .single()
  if (!message) return { ok: false, error: 'Message not found.' }
  if (message.status !== 'approved') return { ok: false, error: 'Only an approved message can get a Gmail draft.' }
  if (message.gmail_draft_id) return { ok: false, error: 'A Gmail draft already exists for this message.' }
  if (message.approved_by !== actor.id) {
    return {
      ok: false,
      error: 'Only the person who approved this message can create its Gmail draft — it goes into their own mailbox.',
    }
  }

  const result = await attemptGmailDraft(supabase, messageId, actor)
  revalidatePath('/review')
  revalidatePath(`/companies/${message.company_id}`)
  return 'warning' in result
    ? { ok: false, error: result.warning, companyId: message.company_id }
    : { ok: true, companyId: message.company_id, messageId, gmailDraftId: result.draftId }
}

export async function rejectMessage(formData: FormData): Promise<MessageActionState> {
  let actor
  try {
    actor = await requirePermission(canWrite, 'reject outreach')
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : 'Not allowed' }
  }

  const messageId = (formData.get('messageId') as string)?.trim()
  const reason = (formData.get('reason') as string)?.trim()
  if (!messageId || !isUuid(messageId)) return { ok: false, error: 'Missing message.' }
  if (!reason) return { ok: false, error: 'A reason is required to reject.' }

  const supabase = await createServerClient()
  const { data: message } = await supabase.from('message').select('company_id').eq('id', messageId).single()
  if (!message) return { ok: false, error: 'Message not found.' }

  const { error } = await supabase
    .from('message')
    .update({ status: 'rejected', rejected_reason: reason })
    .eq('id', messageId)
  if (error) return { ok: false, error: error.message }

  await writeAudit({
    actorId: actor.id,
    actorLabel: actor.fullName,
    event: AUDIT.OUTREACH_REJECTED,
    objectType: 'message',
    objectId: messageId,
    detail: reason,
  })

  revalidatePath('/review')
  return { ok: true, companyId: message.company_id }
}

export async function requestChanges(formData: FormData): Promise<MessageActionState> {
  let actor
  try {
    actor = await requirePermission(canWrite, 'request changes')
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : 'Not allowed' }
  }

  const messageId = (formData.get('messageId') as string)?.trim()
  const note = (formData.get('note') as string)?.trim()
  if (!messageId || !isUuid(messageId)) return { ok: false, error: 'Missing message.' }
  if (!note) return { ok: false, error: 'Add a note explaining what to change.' }

  await writeAudit({
    actorId: actor.id,
    actorLabel: actor.fullName,
    event: AUDIT.CHANGES_REQUESTED,
    objectType: 'message',
    objectId: messageId,
    detail: note,
  })

  revalidatePath('/review')
  return { ok: true }
}

/* ------------------------------------------------------------------ */
/* T7.6 — commercial release                                           */
/* ------------------------------------------------------------------ */

export async function releaseMessage(formData: FormData): Promise<MessageActionState> {
  let actor
  try {
    actor = await requirePermission(canReleaseCommercial, 'release a held draft')
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : 'Not allowed' }
  }

  const messageId = (formData.get('messageId') as string)?.trim()
  if (!messageId || !isUuid(messageId)) return { ok: false, error: 'Missing message.' }

  const supabase = await createServerClient()
  const { data: message } = await supabase.from('message').select('company_id, status').eq('id', messageId).single()
  if (!message) return { ok: false, error: 'Message not found.' }
  if (message.status !== 'held_commercial') return { ok: false, error: 'Only a held draft can be released.' }

  const { error } = await supabase.from('message').update({ released_by: actor.id }).eq('id', messageId)
  if (error) return { ok: false, error: error.message }

  await writeAudit({
    actorId: actor.id,
    actorLabel: actor.fullName,
    event: AUDIT.COMMERCIAL_RELEASED,
    objectType: 'message',
    objectId: messageId,
    detail: 'Released for approval',
  })

  revalidatePath('/review')
  return { ok: true, companyId: message.company_id }
}
