'use server'

/**
 * lib/reply-actions.ts — human-initiated server actions for the Replies screen
 * (T9.2–T9.6). The AI classification itself is generated by lib/ai/triage-runner.ts
 * (service role, like ai_run/research_run and the draft runner); everything here is a
 * person acting on their own RLS-scoped client, same as lib/message-actions.ts and
 * lib/company-actions.ts.
 */
import { revalidatePath } from 'next/cache'
import { createServerClient } from './supabase/server'
import { admin } from './supabase/admin'
import { requirePermission, canWrite } from './session'
import { writeAudit, AUDIT } from './audit'
import { scanPatterns } from './guardrails'
import { buildReplyDraft, suppressKeyFor, categoryLabel, CATEGORY_LABELS, type ReservedPoint } from './replies'
import { triageReply, TriageError } from './ai/triage-runner'
import { AIError } from './ai/client'
import { ROLE_LABELS } from './nav'

export type ReplyActionState = {
  ok: boolean
  error?: string
  replyId?: string
  messageId?: string
  note?: string
}

const isUuid = (s: string) => /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(s)

async function guard(action: string) {
  try {
    return await requirePermission(canWrite, action)
  } catch (err) {
    return { ok: false as const, error: err instanceof Error ? err.message : 'Not allowed' }
  }
}

/**
 * The Commercial Authority, for escalation routing and the authority name in a
 * deferred reply. Executives cannot read other profiles through RLS (the profiles
 * read policy is self + manager/commercial/auditor only), so this one read goes
 * through the service role — a server-side role→user resolution, not a write bypass.
 */
async function commercialAuthority() {
  const { data } = await admin
    .from('profiles')
    .select('id, full_name')
    .eq('role', 'commercial')
    .limit(1)
    .maybeSingle()
  return data
}

/* ------------------------------------------------------------------ */
/* T9.2 — simulate an incoming reply, then classify it                 */
/* ------------------------------------------------------------------ */

export async function simulateReply(formData: FormData): Promise<ReplyActionState> {
  const actor = await guard('simulate a reply')
  if (!('id' in actor)) return actor

  const contactId = (formData.get('contactId') as string)?.trim()
  const body = (formData.get('body') as string)?.trim()
  if (!contactId || !isUuid(contactId)) return { ok: false, error: 'Choose a thread.' }
  if (!body) return { ok: false, error: 'Write the reply text.' }

  const supabase = await createServerClient()
  const { data: contact } = await supabase
    .from('contact')
    .select('company_id, full_name')
    .eq('id', contactId)
    .single()
  if (!contact) return { ok: false, error: 'Contact not found.' }

  // Link the reply to the message we sent that contact, so the thread reads whole.
  const { data: sentMessage } = await supabase
    .from('message')
    .select('id')
    .eq('contact_id', contactId)
    .in('status', ['approved', 'sent'])
    .order('created_at', { ascending: false })
    .limit(1)
    .maybeSingle()

  const { data: reply, error } = await supabase
    .from('reply')
    .insert({
      company_id: contact.company_id,
      contact_id: contactId,
      message_id: sentMessage?.id ?? null,
      body,
      received_at: new Date().toISOString(),
      is_simulated: true,
    })
    .select('id')
    .single()
  if (error || !reply) return { ok: false, error: error?.message ?? 'Could not save the simulated reply.' }

  await writeAudit({
    actorId: actor.id,
    actorLabel: actor.fullName,
    event: AUDIT.REPLY_INGESTED,
    objectType: 'reply',
    objectId: reply.id,
    detail: `Simulated reply from ${contact.full_name}`,
  })

  // Classify immediately — the mock's "Deliver reply" toast shows the result. The
  // reply is already saved, so a classification failure is surfaced, not fatal.
  try {
    const r = await triageReply(reply.id, actor)
    revalidatePath('/replies')
    revalidatePath('/companies')
    return {
      ok: true,
      replyId: reply.id,
      note: `Reply received. AI classified it as: ${categoryLabel(r.category).toLowerCase()} — ${r.nextAction.replace('_', ' ')}.`,
    }
  } catch (err) {
    revalidatePath('/replies')
    const msg = err instanceof AIError || err instanceof TriageError ? err.message : 'Classification failed.'
    return { ok: true, replyId: reply.id, note: `Reply received, but classification failed: ${msg}` }
  }
}

/* ------------------------------------------------------------------ */
/* T9.3 — classify / reclassify                                        */
/* ------------------------------------------------------------------ */

export async function classifyReply(formData: FormData): Promise<ReplyActionState> {
  const actor = await guard('classify replies')
  if (!('id' in actor)) return actor

  const replyId = (formData.get('replyId') as string)?.trim()
  if (!replyId || !isUuid(replyId)) return { ok: false, error: 'Missing reply.' }

  try {
    const r = await triageReply(replyId, actor)
    revalidatePath('/replies')
    revalidatePath('/companies')
    return { ok: true, replyId, note: `Classified: ${categoryLabel(r.category)}` }
  } catch (err) {
    const msg = err instanceof AIError || err instanceof TriageError ? err.message : 'Classification failed.'
    return { ok: false, error: msg }
  }
}

export async function reclassifyReply(formData: FormData): Promise<ReplyActionState> {
  const actor = await guard('reclassify a reply')
  if (!('id' in actor)) return actor

  const replyId = (formData.get('replyId') as string)?.trim()
  const category = (formData.get('category') as string)?.trim()
  if (!replyId || !isUuid(replyId)) return { ok: false, error: 'Missing reply.' }
  if (!category || !(category in CATEGORY_LABELS)) return { ok: false, error: 'Unknown category.' }

  const supabase = await createServerClient()
  const { data: reply } = await supabase.from('reply').select('category').eq('id', replyId).single()
  if (!reply) return { ok: false, error: 'Reply not found.' }

  const { error } = await supabase
    .from('reply')
    .update({ corrected_category: category as never })
    .eq('id', replyId)
  if (error) return { ok: false, error: error.message }

  await writeAudit({
    actorId: actor.id,
    actorLabel: actor.fullName,
    event: AUDIT.AI_RECLASSIFIED,
    objectType: 'reply',
    objectId: replyId,
    detail: `${reply.category ?? 'unclassified'} → ${category}`,
  })

  revalidatePath('/replies')
  return { ok: true, replyId, note: 'Reclassified. Correction stored for model review.' }
}

/* ------------------------------------------------------------------ */
/* T9.5 — draft the technical half of the response                     */
/* ------------------------------------------------------------------ */

export async function draftResponse(formData: FormData): Promise<ReplyActionState> {
  const actor = await guard('draft a reply')
  if (!('id' in actor)) return actor

  const replyId = (formData.get('replyId') as string)?.trim()
  if (!replyId || !isUuid(replyId)) return { ok: false, error: 'Missing reply.' }

  const supabase = await createServerClient()
  const { data: reply } = await supabase
    .from('reply')
    .select('id, company_id, contact_id, message_id, category, answerable, reserved')
    .eq('id', replyId)
    .single()
  if (!reply) return { ok: false, error: 'Reply not found.' }
  if (!reply.category) return { ok: false, error: 'Classify this reply before drafting a response.' }

  const answerable = (reply.answerable ?? []) as string[]
  const reserved = (reply.reserved ?? []) as unknown as ReservedPoint[]

  const [{ data: contact }, { data: message }, { data: company }] = await Promise.all([
    reply.contact_id
      ? supabase.from('contact').select('full_name').eq('id', reply.contact_id).maybeSingle()
      : Promise.resolve({ data: null }),
    reply.message_id
      ? supabase.from('message').select('subject').eq('id', reply.message_id).maybeSingle()
      : Promise.resolve({ data: null }),
    supabase.from('company').select('name, market').eq('id', reply.company_id).single(),
  ])

  const commercial = await commercialAuthority()

  const draft = buildReplyDraft({
    contactName: contact?.full_name ?? null,
    senderName: actor.fullName,
    senderTitle: ROLE_LABELS[actor.role],
    answerable,
    reserved,
    authorityName: commercial?.full_name ?? 'our Commercial Authority',
    market: company?.market ?? '',
    threadSubject: message?.subject ?? '',
  })

  // The deterministic draft is built to be clean, but a keyword must never sail
  // through on a promise. If it somehow trips, refuse to draft and point at
  // escalation rather than creating a held message the executive cannot insert.
  const findings = scanPatterns(draft.body)
  if (findings.length) {
    return {
      ok: false,
      error: 'The prepared reply would touch a reserved matter. Escalate the commercial points instead of drafting here.',
    }
  }

  const { data: msg, error } = await supabase
    .from('message')
    .insert({
      company_id: reply.company_id,
      contact_id: reply.contact_id,
      kind: 'reply',
      subject: draft.subject,
      ai_body: draft.body,
      why: [
        ...answerable.map((a) => `Answering: ${a}`),
        ...(draft.deferredCount ? [`${draft.deferredCount} commercial point(s) acknowledged and deferred`] : []),
      ],
      status: 'awaiting_approval',
    })
    .select('id')
    .single()
  if (error || !msg) return { ok: false, error: error?.message ?? 'Could not save the reply draft.' }

  await writeAudit({
    actorId: actor.id,
    actorLabel: actor.fullName,
    event: AUDIT.REPLY_DRAFTED,
    objectType: 'message',
    objectId: msg.id,
    detail: `Reply draft for ${company?.name ?? 'company'}${draft.deferredCount ? ` — ${draft.deferredCount} point(s) deferred` : ''}`,
  })

  revalidatePath('/replies')
  revalidatePath('/review')
  revalidatePath(`/companies/${reply.company_id}`)
  return {
    ok: true,
    replyId,
    messageId: msg.id,
    note: draft.deferredCount
      ? 'Reply drafted and the commercial half flagged for escalation.'
      : 'Reply drafted and sent to the review queue.',
  }
}

/* ------------------------------------------------------------------ */
/* T9.5 — escalate the reserved half to a Commercial Authority         */
/* ------------------------------------------------------------------ */

export async function escalateCommercial(formData: FormData): Promise<ReplyActionState> {
  const actor = await guard('escalate to commercial')
  if (!('id' in actor)) return actor

  const replyId = (formData.get('replyId') as string)?.trim()
  if (!replyId || !isUuid(replyId)) return { ok: false, error: 'Missing reply.' }

  const supabase = await createServerClient()
  const { data: reply } = await supabase
    .from('reply')
    .select('company_id, contact_id')
    .eq('id', replyId)
    .single()
  if (!reply) return { ok: false, error: 'Reply not found.' }

  const [{ data: company }, { data: contact }] = await Promise.all([
    supabase.from('company').select('name, stage').eq('id', reply.company_id).single(),
    reply.contact_id
      ? supabase.from('contact').select('full_name').eq('id', reply.contact_id).maybeSingle()
      : Promise.resolve({ data: null }),
  ])
  if (!company) return { ok: false, error: 'Company not found.' }

  const commercial = await commercialAuthority()
  const authorityName = commercial?.full_name ?? 'Commercial Authority'
  const dueTomorrow = new Date(Date.now() + 864e5).toISOString().slice(0, 10)

  const { error: taskError } = await supabase.from('task').insert({
    company_id: reply.company_id,
    title: `Commercial terms — ${company.name}${contact?.full_name ? ` (${contact.full_name})` : ''}`,
    assignee_id: commercial?.id ?? null,
    due_on: dueTomorrow,
    blocks_stage: true,
  })
  if (taskError) return { ok: false, error: taskError.message }

  await writeAudit({
    actorId: actor.id,
    actorLabel: actor.fullName,
    event: AUDIT.REPLY_ESCALATED,
    objectType: 'reply',
    objectId: replyId,
    detail: `Escalated to ${authorityName} — 24h flag`,
  })

  if (company.stage !== 'commercial_discussion') {
    const { error: stageError } = await supabase
      .from('company')
      .update({ stage: 'commercial_discussion' })
      .eq('id', reply.company_id)
    if (stageError) return { ok: false, error: stageError.message }

    await writeAudit({
      actorId: actor.id,
      actorLabel: actor.fullName,
      event: AUDIT.STAGE_CHANGED,
      objectType: 'company',
      objectId: reply.company_id,
      detail: 'Stage → commercial_discussion',
    })
  }

  revalidatePath('/replies')
  revalidatePath('/meetings')
  revalidatePath(`/companies/${reply.company_id}`)
  return { ok: true, replyId, note: `Escalated to ${authorityName}, Commercial Authority.` }
}

/* ------------------------------------------------------------------ */
/* T9.5 — book a call / move to nurture                                */
/* ------------------------------------------------------------------ */

export async function bookCall(formData: FormData): Promise<ReplyActionState> {
  const actor = await guard('book a meeting')
  if (!('id' in actor)) return actor

  const replyId = (formData.get('replyId') as string)?.trim()
  if (!replyId || !isUuid(replyId)) return { ok: false, error: 'Missing reply.' }

  const supabase = await createServerClient()
  const { data: reply } = await supabase
    .from('reply')
    .select('company_id, reserved')
    .eq('id', replyId)
    .single()
  if (!reply) return { ok: false, error: 'Reply not found.' }

  const reserved = (reply.reserved ?? []) as unknown as ReservedPoint[]
  const requiresCommercial = reserved.length > 0
  const startsAt = new Date(Date.now() + 7 * 864e5).toISOString()

  const { data: meeting, error } = await supabase
    .from('meeting')
    .insert({
      company_id: reply.company_id,
      starts_at: startsAt,
      purpose: requiresCommercial ? 'Commercial discussion — terms' : 'Introductory call',
      requires_commercial: requiresCommercial,
    })
    .select('id')
    .single()
  if (error || !meeting) return { ok: false, error: error?.message ?? 'Could not schedule the meeting.' }

  await writeAudit({
    actorId: actor.id,
    actorLabel: actor.fullName,
    event: AUDIT.MEETING_SCHEDULED,
    objectType: 'meeting',
    objectId: meeting.id,
    detail: requiresCommercial ? 'Commercial discussion — Commercial Authority must attend' : 'Introductory call',
  })

  const { error: stageError } = await supabase
    .from('company')
    .update({ stage: 'meeting' })
    .eq('id', reply.company_id)
  if (!stageError) {
    await writeAudit({
      actorId: actor.id,
      actorLabel: actor.fullName,
      event: AUDIT.STAGE_CHANGED,
      objectType: 'company',
      objectId: reply.company_id,
      detail: 'Stage → meeting',
    })
  }

  revalidatePath('/replies')
  revalidatePath('/meetings')
  return {
    ok: true,
    replyId,
    note: requiresCommercial ? 'Call booked — Commercial Authority must attend.' : 'Call booked.',
  }
}

export async function nurtureReply(formData: FormData): Promise<ReplyActionState> {
  const actor = await guard('move a reply to nurture')
  if (!('id' in actor)) return actor

  const replyId = (formData.get('replyId') as string)?.trim()
  if (!replyId || !isUuid(replyId)) return { ok: false, error: 'Missing reply.' }

  const supabase = await createServerClient()
  const { data: reply } = await supabase
    .from('reply')
    .select('company_id, revisit_on')
    .eq('id', replyId)
    .single()
  if (!reply) return { ok: false, error: 'Reply not found.' }

  const { error } = await supabase
    .from('company')
    .update({ stage: 'nurture' })
    .eq('id', reply.company_id)
  if (error) return { ok: false, error: error.message }

  await writeAudit({
    actorId: actor.id,
    actorLabel: actor.fullName,
    event: AUDIT.STAGE_CHANGED,
    objectType: 'company',
    objectId: reply.company_id,
    detail: 'Stage → nurture',
  })

  if (reply.revisit_on) {
    const { error: taskError } = await supabase.from('task').insert({
      company_id: reply.company_id,
      title: 'Revisit after buyer said not now',
      assignee_id: actor.id,
      due_on: reply.revisit_on,
      blocks_stage: false,
    })
    if (taskError) return { ok: false, error: taskError.message }
  }

  revalidatePath('/replies')
  revalidatePath(`/companies/${reply.company_id}`)
  return { ok: true, replyId, note: 'Moved to Nurture.' }
}

/* ------------------------------------------------------------------ */
/* T9.6 — no further contact, permanent, SQL-enforced                  */
/* ------------------------------------------------------------------ */

export async function noFurtherContact(formData: FormData): Promise<ReplyActionState> {
  const actor = await guard('record no further contact')
  if (!('id' in actor)) return actor

  const replyId = (formData.get('replyId') as string)?.trim()
  if (!replyId || !isUuid(replyId)) return { ok: false, error: 'Missing reply.' }

  const supabase = await createServerClient()
  const { data: reply } = await supabase
    .from('reply')
    .select('company_id, contact_id')
    .eq('id', replyId)
    .single()
  if (!reply) return { ok: false, error: 'Reply not found.' }

  const [{ data: contact }, { data: company }] = await Promise.all([
    reply.contact_id
      ? supabase.from('contact').select('email').eq('id', reply.contact_id).maybeSingle()
      : Promise.resolve({ data: null }),
    supabase.from('company').select('website, name').eq('id', reply.company_id).single(),
  ])

  const key = suppressKeyFor(contact?.email ?? null, company?.website ?? null)
  if (!key) return { ok: false, error: 'No address on record to suppress.' }

  const { error: suppressError } = await supabase
    .from('suppression')
    .insert({ email_or_domain: key, reason: 'Requested no further contact' })
  // Already suppressed is not a failure — the goal is already achieved.
  if (suppressError && suppressError.code !== '23505') return { ok: false, error: suppressError.message }

  await writeAudit({
    actorId: actor.id,
    actorLabel: actor.fullName,
    event: AUDIT.SUPPRESSED,
    objectType: 'company',
    objectId: reply.company_id,
    detail: `No further contact — "${key}" suppressed permanently`,
  })

  const { error: stageError } = await supabase
    .from('company')
    .update({ stage: 'no_contact' })
    .eq('id', reply.company_id)
  if (stageError) return { ok: false, error: stageError.message }

  await writeAudit({
    actorId: actor.id,
    actorLabel: actor.fullName,
    event: AUDIT.STAGE_CHANGED,
    objectType: 'company',
    objectId: reply.company_id,
    detail: 'Stage → no_contact',
  })

  revalidatePath('/replies')
  revalidatePath(`/companies/${reply.company_id}`)
  return { ok: true, replyId, note: 'No further contact recorded. This cannot be undone.' }
}
